version: '3'

services:
  app:
    container_name: sing_along_zlin
    build: .
    ports:
      - '91:3000'
    links:
      - mongo
    volumes:
      - ../../:/usr/src/app/
      - ./run.sh:/run.sh
      - app-node-modules:/usr/src/app/node_modules/

  mongo:
    container_name: sing_along_zlin_mongo
    image: mongo:4.0.4
    expose:
      - '27017'

volumes:
  app-node-modules: